"""
Structured refusal taxonomy -- Tier 1 safety module.

NO LLM IMPORTS IN THIS FILE (see CLAUDE.md). Every refusal is a fixed,
machine-readable code plus a human-readable detail string; nothing here is
generated, only selected from the fixed set below and filled in with the
specific context that triggered it.

"Refusals are logged as richly as successes" -- a Refusal carries enough
structured context (in `context`) to reconstruct exactly why a transaction
was refused without needing to re-run anything, which is the actual point:
an audit trail that answers "why did the agent get refused" without
guessing.

Twelve codes across six categories -- see docs/refusal_codes.md for the
full table (regenerated by refusal_codes_table(), not hand-maintained, so
the doc can never drift from the enum).
"""

from dataclasses import dataclass, field
from enum import Enum
from typing import Any


class RefusalCategory(str, Enum):
    AUTH = "auth"
    POLICY = "policy"
    COMPATIBILITY = "compatibility"
    AVAILABILITY = "availability"
    INTEGRITY = "integrity"
    INFRASTRUCTURE = "infrastructure"


class RefusalCode(str, Enum):
    # --- auth: the Intent Mandate itself doesn't check out ---
    INVALID_SIGNATURE = "invalid_signature"
    MANDATE_EXPIRED = "mandate_expired"

    # --- policy: the mandate checks out, but the request violates its own stated limits ---
    OVER_PRICE_CEILING = "over_price_ceiling"
    CUMULATIVE_CEILING_EXCEEDED = "cumulative_ceiling_exceeded"
    CATEGORY_NOT_ALLOWED = "category_not_allowed"

    # --- compatibility: a requested item's fit-for-purpose claim doesn't hold up ---
    INCOMPATIBLE_ITEM = "incompatible_item"
    UNVERIFIED_COMPATIBILITY = "unverified_compatibility"

    # --- availability: the item isn't there to sell, or isn't safe to sell ---
    OUT_OF_STOCK = "out_of_stock"
    SKU_NOT_PUBLISHED = "sku_not_published"

    # --- integrity: something that should be internally consistent isn't ---
    NONCE_REPLAYED = "nonce_replayed"
    CART_TOTAL_MISMATCH = "cart_total_mismatch"

    # --- infrastructure: the failure is ours, not the request's ---
    PAYMENT_PROVIDER_ERROR = "payment_provider_error"
    INTERNAL_ERROR = "internal_error"


_CATEGORY_OF: dict[RefusalCode, RefusalCategory] = {
    RefusalCode.INVALID_SIGNATURE: RefusalCategory.AUTH,
    RefusalCode.MANDATE_EXPIRED: RefusalCategory.AUTH,
    RefusalCode.OVER_PRICE_CEILING: RefusalCategory.POLICY,
    RefusalCode.CUMULATIVE_CEILING_EXCEEDED: RefusalCategory.POLICY,
    RefusalCode.CATEGORY_NOT_ALLOWED: RefusalCategory.POLICY,
    RefusalCode.INCOMPATIBLE_ITEM: RefusalCategory.COMPATIBILITY,
    RefusalCode.UNVERIFIED_COMPATIBILITY: RefusalCategory.COMPATIBILITY,
    RefusalCode.OUT_OF_STOCK: RefusalCategory.AVAILABILITY,
    RefusalCode.SKU_NOT_PUBLISHED: RefusalCategory.AVAILABILITY,
    RefusalCode.NONCE_REPLAYED: RefusalCategory.INTEGRITY,
    RefusalCode.CART_TOTAL_MISMATCH: RefusalCategory.INTEGRITY,
    RefusalCode.PAYMENT_PROVIDER_ERROR: RefusalCategory.INFRASTRUCTURE,
    RefusalCode.INTERNAL_ERROR: RefusalCategory.INFRASTRUCTURE,
}

_DESCRIPTION_OF: dict[RefusalCode, str] = {
    RefusalCode.INVALID_SIGNATURE: "The Intent Mandate's Ed25519 signature does not verify against its claimed public key.",
    RefusalCode.MANDATE_EXPIRED: "The Intent Mandate's expiry timestamp has passed.",
    RefusalCode.OVER_PRICE_CEILING: "The proposed cart total exceeds the Intent Mandate's max_amount.",
    RefusalCode.CUMULATIVE_CEILING_EXCEEDED: (
        "Combined with prior successful transactions already recorded under this intent_mandate_id, "
        "this cart would exceed the Intent Mandate's max_amount -- each individual transaction was "
        "under the ceiling, but the running total is not."
    ),
    RefusalCode.CATEGORY_NOT_ALLOWED: "A requested SKU's category is outside the Intent Mandate's allowed_categories.",
    RefusalCode.INCOMPATIBLE_ITEM: "pipeline/verify.py could not verify a claimed compatibility relationship for a requested item.",
    RefusalCode.UNVERIFIED_COMPATIBILITY: "A compatibility claim exists but carries no machine-checkable proof (e.g. the underlying attribute is quarantined).",
    RefusalCode.OUT_OF_STOCK: "A requested SKU has no available stock.",
    RefusalCode.SKU_NOT_PUBLISHED: "A requested SKU is quarantined or otherwise not published -- not agent-purchasable.",
    RefusalCode.NONCE_REPLAYED: "The Intent Mandate's nonce has already been used (replay attempt).",
    RefusalCode.CART_TOTAL_MISMATCH: "Post-payment reconciliation found the Razorpay-side amount doesn't match our recorded cart total.",
    RefusalCode.PAYMENT_PROVIDER_ERROR: "Razorpay returned an error independent of mandate/cart validity.",
    RefusalCode.INTERNAL_ERROR: "An unexpected internal failure -- fail closed rather than guess.",
}


@dataclass(frozen=True)
class Refusal:
    code: RefusalCode
    detail: str  # specific, human-readable -- "why THIS request", not the generic category description
    context: dict[str, Any] = field(default_factory=dict)  # structured facts for the audit trail

    @property
    def category(self) -> RefusalCategory:
        return _CATEGORY_OF[self.code]

    def to_dict(self) -> dict[str, Any]:
        return {
            "code": self.code.value,
            "category": self.category.value,
            "detail": self.detail,
            "context": self.context,
        }


def refusal_codes_table() -> list[dict[str, str]]:
    """Row data for docs/refusal_codes.md -- generated from this enum, not
    hand-maintained, so the doc can't drift from the code."""
    return [
        {"code": code.value, "category": _CATEGORY_OF[code].value, "description": _DESCRIPTION_OF[code]}
        for code in RefusalCode
    ]
