"""
Generates docs/refusal_codes.md from surface.refusal.refusal_codes_table() --
the table is derived from the RefusalCode enum, not hand-maintained, so the
doc can never drift from the actual code.

Usage:
    python scripts/build_refusal_docs.py
"""

from pathlib import Path

from surface.refusal import RefusalCategory, refusal_codes_table

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "docs" / "refusal_codes.md"


def main():
    rows = refusal_codes_table()
    lines = [
        "# Refusal codes",
        "",
        (
            "Generated by `scripts/build_refusal_docs.py` from `surface/refusal.py`'s "
            "`RefusalCode` enum -- do not hand-edit, regenerate instead."
        ),
        "",
        (
            "Every refusal `surface/gate.py` produces carries one of these codes, a "
            "specific human-readable detail string, and a structured `context` dict "
            'for the audit trail. "Refusals are logged as richly as successes" '
            "(see `docs/CLAUDE.md`)."
        ),
        "",
    ]
    for category in RefusalCategory:
        lines.append(f"## {category.value}")
        lines.append("")
        lines.append("| code | description |")
        lines.append("|---|---|")
        for row in rows:
            if row["category"] == category.value:
                lines.append(f"| `{row['code']}` | {row['description']} |")
        lines.append("")

    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {len(rows)} refusal codes to {OUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
